-- DELETE 1: (REMOVER RN ESPECÍFICO).
DELETE FROM recem_nascido
WHERE id_parto = 3;

-- DELETE 2: (APAGAR UM PARTO SEM RN ASSOCIADO, COLOCADO POR ENGANO).
DELETE FROM partos
WHERE id_parto = 4;

-- DELETE 3: (REMOVER PACIENTE SEM PARTO ASSOCIADO).
DELETE FROM pacientes
WHERE id_paciente = 5;
